<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rover">
  <xacro:property name="wheel_radius" value="0.10" />
  <xacro:property name="wheel_width" value="0.02" />
  <xacro:property name="body_height" value="0.05" />
  <xacro:property name="body_width" value="0.15" />
  <xacro:property name="body_length" value="0.4" />
  <xacro:property name="leg_height" value="0.05" />
  <xacro:property name="leg_width" value="0.02" />
  <xacro:property name="leg_length" value="0.02" />

  <gazebo reference="body">
    <material>Gazebo/White</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
 </gazebo>

  <link name="body">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="5"/>
      <inertia ixx="${(5/12) * (body_width * body_width + body_height* body_height)}" ixy="0" ixz="0" iyy="${(5/12) * (body_length * body_length + body_height * body_height)}" iyz="0" izz="${(5/12) * (body_width * body_width + body_length * body_length)}" />
    </inertial>
  </link>

  <link name="lLeg">
    <visual>
      <geometry>
        <box size="${leg_length} ${leg_width} ${leg_height}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <box size="${leg_length} ${leg_width} ${leg_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="${(1/12) * (leg_width * leg_width + leg_height* leg_height)}" ixy="0" ixz="0" iyy="${(1/12) * (leg_length * leg_length + leg_height * leg_height)}" iyz="0" izz="${(1/12) * (leg_width * leg_width + leg_length * leg_length)}" />
    </inertial>
  </link>

  <joint name="lDifJoint" type="continuous">
    <parent link="body"/>
    <child link="lLeg"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${body_length/2 - 0.03} ${body_width/2 + wheel_width/2} -${body_height/2}"/>
  </joint>

  <link name="rLeg">
    <visual>
      <geometry>
        <box size="${leg_length} ${leg_width} ${leg_height}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <box size="${leg_length} ${leg_width} ${leg_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="${(1/12) * (leg_width * leg_width + leg_height* leg_height)}" ixy="0" ixz="0" iyy="${(1/12) * (leg_length * leg_length + leg_height * leg_height)}" iyz="0" izz="${(1/12) * (leg_width * leg_width + leg_length * leg_length)}" />
    </inertial>
  </link>

  <joint name="rDifJoint" type="continuous">
    <parent link="body"/>
    <child link="rLeg"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${body_length/2 - 0.03} -${body_width/2 + wheel_width/2} -${body_height/2}"/>
  </joint>



  <xacro:macro name="wheel_link" params="name radius width mass">
    <gazebo reference="${name}">
      <material>Gazebo/Grey</material>
      <mu1>0.84</mu1>
      <mu2>0.84</mu2>
   </gazebo>

    <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="${width}" radius="${radius}"/>
        </geometry>
      </visual>

      <collision>
        <geometry>
          <cylinder length="${width}" radius="${radius}"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * (3 * radius * radius + width * width)}" ixy="0" ixz="0" iyy="${(1/12) * mass * (3 * radius * radius + width * width)}" iyz="0" izz="${(1/2) * mass * radius * radius}"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:wheel_link name="wFL" radius="${wheel_radius}" width="${wheel_width}" mass="2"/>

  <joint name="jFL" type="continuous">
    <parent link="lLeg"/>
    <child link="wFL"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 ${leg_width/2} ${leg_length/2}" rpy="${pi/2} 0 0" />
    <dynamics friction="0.5"/>
  </joint>

  <xacro:wheel_link name="wBL" radius="${wheel_radius}" width="${wheel_width}" mass="2"/>

  <joint name="jBL" type="continuous">
    <parent link="body"/>
    <child link="wBL"/>
    <axis xyz="0 0 1"/>
    <origin xyz="-${body_length/2 - 0.03} ${body_width/2 + wheel_width/2} 0" rpy="${pi/2} 0 0" />
    <dynamics friction="0.5"/>
  </joint>

  <xacro:wheel_link name="wFR" radius="${wheel_radius}" width="${wheel_width}" mass="2"/>

  <joint name="jFR" type="continuous">
    <parent link="rLeg"/>
    <child link="wFR"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 -${leg_width/2} ${leg_length/2}" rpy="${pi/2} 0 0" />
    <dynamics friction="0.5"/>
  </joint>

  <xacro:wheel_link name="wBR" radius="${wheel_radius}" width="${wheel_width}" mass="2"/>

  <joint name="jBR" type="continuous">
    <parent link="body"/>
    <child link="wBR"/>
    <axis xyz="0 0 1"/>
    <origin xyz="-${body_length/2 - 0.03} -${body_width/2 + wheel_width/2} 0" rpy="${pi/2} 0 0" />
    <dynamics friction="0.5"/>
  </joint>


  <gazebo>
    <plugin name="rover_plugin" filename="librover_plugin.so"> </plugin>
  </gazebo>
</robot>

